### ISSUE TITLE
[Bug-Candidate]: Echidna hangs forever 

### ISSUE THREAD

**Issue by nuliknol** [crytic/echidna#1015]
### Describe the issue:

When running  `~/bin/echidna . Whatever.sol` the command hags forever. The `.` is the Hardhat directory where a complete set of contracts is located.

### Code example to reproduce the issue:

I don't know how to reproduce it because I don't understand why it hangs

### Version:

2.1.1

### Relevant log output:

```shell
Apparently the process hangs forever because the hardhat command is invoked because it asks for `console` . I don't understand why a script asks for console, because there won't be any human interaction but this is what I am seeing , so probably there is a bug somewhere in launching hardhat. This is the output of `ps` command:

user       35342  0.0  0.0  17484  5204 pts/33   Ss   abr03   0:00              |   \_ bash
user      123630  0.0  0.3 1073791216 29692 pts/33 Sl+ 13:06   0:00              |   |   \_ /home/user/bin/echidna . BWTest.sol --config /home/user/eth/tests/echidna-bw.yaml --contract BWTest --test-mode property
user      123635  0.1  0.3  41408 26764 pts/33   S+   13:06   0:00              |   |       \_ /usr/bin/python3 /home/user/.local/bin/crytic-compile --solc-remaps @openzeppelin=/home/user/eth/dev/MyProject-Echidna/node_modules/@openzeppelin --solc-args=--optimize --solc-disable-warnings --export-format solc .
user      123688  0.3  0.7 708840 57232 pts/33   Sl+  13:06   0:01              |   |           \_ npm exec hardhat console --no-compile
user      123699  0.0  0.0   2892   956 pts/33   S+   13:06   0:00              |   |               \_ sh -c hardhat console --no-compile
user      123700  2.8  1.2 21959336 104812 pts/33 Sl+ 13:06   0:08              |   |                   \_ node /home/user/eth/dev/MyProject-Echidna/node_modules/.bin/hardhat console --no-compile
user      123711  2.5  1.2 11468392 98892 pts/33 Sl+  13:06   0:07              |   |                       \_ /usr/local/node-v16.15.0-linux-x64/bin/node --experimental-repl-await --require /home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/register

So, the process 123711 makes the whole chain of processes wait forever because the 123711 process opens a console and since nobody types anything at the console all the parent processes enter "wait" state and nothing happens.
```

**Comment by elopez** [comment]
Hi! Thanks for the report. The `hardhat console` command is expected, it is invoked non-interactively by crytic-compile to auto-detect the hardhat artifact path, by launching it, running `console.log(JSON.stringify(config.paths))` and closing the pipe: https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/hardhat.py#L303-L312

It should, however, not be hanging. Can you confirm that `npx hardhat console --no-compile` works for you, and that running `console.log(JSON.stringify(config.paths))` on the hardhat console returns something reasonable that does not hang your hardhat console?

**Comment by nuliknol** [comment]
@elopez 

yes, `hardhat console` works , the command `console.log(JSON.stringify(config.paths))` returns "undefined", here is how it looks like:

```
user@desk :~/eth/dev/MyProject-Echidna$ npx hardhat console --no-compile
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> console.log(JSON.stringify(config.paths))
{"root":"/home/user/eth/dev/MyProject-Echidna","configFile":"/home/user/eth/dev/MyProject-Echidna/hardhat.config.js","sources":"/home/user/eth/dev/MyProject-Echidna/contracts","cache":"/home/user/eth/dev/MyProject-Echidna/cache","artifacts":"/home/user/eth/dev/MyProject-Echidna/artifacts","tests":"/home/user/eth/dev/MyProject-Echidna/test"}
undefined
> config.paths
{
  root: '/home/user/eth/dev/MyProject-Echidna',
  configFile: '/home/user/eth/dev/MyProject-Echidna/hardhat.config.js',
  sources: '/home/user/eth/dev/MyProject-Echidna/contracts',
  cache: '/home/user/eth/dev/MyProject-Echidna/cache',
  artifacts: '/home/user/eth/dev/MyProject-Echidna/artifacts',
  tests: '/home/user/eth/dev/MyProject-Echidna/test'
}
> 
```

the `console.log()` will return "undefined" always, here again:

```
> JSON.stringify(config.paths)
'{"root":"/home/user/eth/dev/MyProject-Echidna","configFile":"/home/user/eth/dev/MyProject-Echidna/hardhat.config.js","sources":"/home/user/eth/dev/MyProject-Echidna/contracts","cache":"/home/user/eth/dev/MyProject-Echidna/cache","artifacts":"/home/user/eth/dev/MyProject-Echidna/artifacts","tests":"/home/user/eth/dev/MyProject-Echidna/test"}'
> console.log(JSON.stringify(config.paths))
{"root":"/home/user/eth/dev/MyProject-Echidna","configFile":"/home/user/eth/dev/MyProject-Echidna/hardhat.config.js","sources":"/home/user/eth/dev/MyProject-Echidna/contracts","cache":"/home/user/eth/dev/MyProject-Echidna/cache","artifacts":"/home/user/eth/dev/MyProject-Echidna/artifacts","tests":"/home/user/eth/dev/MyProject-Echidna/test"}
undefined
> console.log("data")
data
undefined
> 
```

I think you have to call it without the "console.log" , just simply the argument

**Comment by ggrieco-tob** [comment]
Can you re-test with `crytic-compile .`? If it still hangs, then we should move this discussion to that issue tracker.

**Comment by nuliknol** [comment]
@ggrieco-tob `crytic-compile` doesn't succeed, it doesn't find ERC20FlashMint file, but I don't have this problem with hardhat:

```
user@desk :~/eth/dev/MyProject-Echidna$ crytic-compile .
INFO:CryticCompile:'npx hardhat clean' running (wd: /home/user/eth/dev/MyProject-Echidna)
ERROR:CryticCompile:'npx' returned non-zero exit code 1
ERROR:CryticCompile:/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/src/internal/artifacts.ts:681
stderr:     throw new HardhatError(ERRORS.ARTIFACTS.NOT_FOUND, {
stderr:           ^
stderr: HardhatError: HH700: Artifact for contract "@openzeppelin/contracts/token/ERC20/extensions/ERC20FlashMint.sol:ERC20FlashMint" not found. Did you mean "@openzeppelin/contracts/token/ERC20/extensions/ERC20FlashMint.sol:ERC20FlashMint"?
stderr:     at Artifacts._handleWrongArtifactForFullyQualifiedName (/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/src/internal/artifacts.ts:681:11)
stderr:     at Artifacts._getValidArtifactPathFromFullyQualifiedName (/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/src/internal/artifacts.ts:633:21)
stderr:     at Artifacts._getArtifactPath (/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/src/internal/artifacts.ts:504:16)
stderr:     at Artifacts.readArtifact (/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/src/internal/artifacts.ts:71:26)
stderr:     at Decoder._updateArtifacts (/home/user/eth/dev/MyProject-Echidna/node_modules/hardhat-tracer/src/decoder.ts:41:24)
INFO:CryticCompile:'npx hardhat clean --global' running (wd: /home/user/eth/dev/MyProject-Echidna)
```

after showing this error `crytic-compile` hangs forever  and the `ps` command shows the same problem as in the first post:

```

user       57932  0.0  0.0  17140  4676 pts/29   Ss   abr04   0:02              |   \_ bash
user      125754  0.2  0.3  41396 26612 pts/29   S+   14:29   0:00              |   |   \_ /usr/bin/python3 /home/user/.local/bin/crytic-compile .
user      125802  0.8  0.7 708592 57108 pts/29   Sl+  14:29   0:01              |   |       \_ npm exec hardhat console --no-compile
user      125813  0.0  0.0   2892   964 pts/29   S+   14:29   0:00              |   |           \_ sh -c hardhat console --no-compile
user      125814  5.0  1.2 21894696 102040 pts/29 Sl+ 14:29   0:06              |   |               \_ node /home/user/eth/dev/MyProject-Echidna/node_modules/.bin/hardhat console --no-compile
user      125826  4.6  1.2 11401784 97868 pts/29 Sl+  14:29   0:05              |   |                   \_ /usr/local/node-v16.15.0-linux-x64/bin/node --experimental-repl-await --require /home/user/eth/dev/MyProject-Echidna/node_modules/hardhat/register
```

**Comment by nuliknol** [comment]
by the way, is there a flag to run Echidna with skipped compilation step? Because I can compile the contracts elsewhere and leave combined-json at some path where Echidna could get it and from there start the test session. This would remove lots of potential problems with compilation.

**Comment by elopez** [comment]
> by the way, is there a flag to run Echidna with skipped compilation step? 

you can run echidna with `cryticArgs: ['--ignore-compile']` on the config to skip the compilation

**Comment by elopez** [comment]
The hardhat console behaves slightly differently when you call it non-interactively:

```
% echo "console.log(JSON.stringify(config.paths))" | npx hardhat console --no-compile
{"root":"/Users/emilio/test","configFile":"/Users/emilio/test/hardhat.config.js","sources":"/Users/emilio/test/contracts","cache":"/Users/emilio/test/cache","artifacts":"/Users/emilio/test/artifacts","tests":"/Users/emilio/test/test"}
emilio@mbpro test % npx hardhat --version
2.13.0
emilio@mbpro test % node --version
v18.13.0
```

Maybe your node or hardhat version behave differently?

if you call it without `console.log` it won't print anything

**Comment by nuliknol** [comment]
@elopez 

well , both commands (with console.log or without) as you typed them above hang forever on my machine, or better said, they don't exit right away.

```
user@desk :~/eth/dev/MyProject-Echidna/contracts$ npx hardhat --version
2.12.7
user@desk :~/eth/dev/MyProject-Echidna/contracts$ node --version
v16.15.0
user@desk :~/eth/dev/MyProject-Echidna/contracts$ 
```

Yes, omitting `console.log()` doesn't print anything when sending the command via `echo` through the pipe.

**Comment by nuliknol** [comment]
@elopez 

1. updating node to 19.8 didn't help
2. updating node to 18.5 didn't help
3. updating hardhat to 2.13.0 didn't help

but this did help:

```
user@desk :~/eth/dev/MyProject-Echidna/contracts$ echo -n "console.log(JSON.stringify(config.paths));process.exit()" | npx hardhat console --no-compile
{"root":"/home/user/eth/dev/MyProject-Echidna","configFile":"/home/user/eth/dev/MyProject-Echidna/hardhat.config.js","sources":"/home/user/eth/dev/MyProject-Echidna/contracts","cache":"/home/user/eth/dev/MyProject-Echidna/cache","artifacts":"/home/user/eth/dev/MyProject-Echidna/artifacts","tests":"/home/user/eth/dev/MyProject-Echidna/test"}
user@desk :~/eth/dev/MyProject-Echidna/contracts$ 
```

it now exits to the shell
