### ISSUE TITLE
[Bug-Candidate]: at ghcr.io/crytic/echidna/echidna:v2.2.0 ，urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

### ISSUE THREAD

**Issue by Scorpiondeng** [crytic/echidna#1076]
### Describe the issue:

`root@81e63b00e90e:/# solc-select use 0.8.18
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/bin/solc-select", line 8, in <module>
    sys.exit(solc_select())
  File "/venv/lib/python3.8/site-packages/solc_select/__main__.py", line 61, in solc_select
    switch_global_version(args.get(USE_VERSION), args.get("always_install"))
  File "/venv/lib/python3.8/site-packages/solc_select/solc_select.py", line 176, in switch_global_version
    elif version in get_available_versions():
  File "/venv/lib/python3.8/site-packages/solc_select/solc_select.py", line 230, in get_available_versions
    github_json = urllib.request.urlopen(list_url).read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>`

solc-select does not work

### Code example to reproduce the issue:

N/A

### Version:

Echidna 2.2.0
slither 0.9.2

**Comment by ggrieco-tob** [comment]
Hi, thanks for the report.

This looks like a solc-select issue, so please copy this issue into their [github issue tracker](https://github.com/crytic/solc-select/issues).
