### ISSUE TITLE
Install info for Hardhat and NPX in Docker?

### ISSUE THREAD

**Issue by n00b21337** [crytic/echidna#1106]
### Describe the desired feature

I am trying to run Echidna with this command/container
$ docker run --rm -it -v `pwd`:/src ghcr.io/crytic/echidna/echidna

But when I try to run it on my contract I get this, I am using hardhat and it was said that here that it should use framework 
https://github.com/crytic/echidna/issues/793 

Wondering how can it do that when there is no node/npm/npx installed on docker container and if should it be there by default?

This is the output from container that I am getting.

```
echidna . --contract TestStakingRegistry
[2023-08-18 17:19:11.10] Compiling .... Done! (0.132292953s)
echidna: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Cannot execute `npx`, is it installed and in PATH?
ERROR:CryticCompile:Cannot execute `npx`, is it installed and in PATH?
INFO:CryticCompile:Problem executing hardhat to fetch configuration, using defaults: [Errno 2] No such file or directory: 'npx'
INFO:CryticCompile:'npx hardhat compile --force' running
Traceback (most recent call last):
  File "/venv/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/crytic_compile/__main__.py", line 193, in main
    compilations = compile_all(**vars(args))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/venv/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 177, in compile
    with subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npx'
```

**Comment by n00b21337** [comment]
I found this now as solution in issue below

```
nvm install 16
nvm use 16
echidna ....
```

https://github.com/crytic/echidna/issues/1044

It would be nice to add it maybe to install info for docker
