### ISSUE TITLE
Github action failing with "FileNotFoundError: [Errno 2] No such file or directory: 'forge"

### ISSUE THREAD

**Issue by haythemsellami** [crytic/echidna#1284]
### Describe the issue:

Following the mentioned github action script https://github.com/crytic/echidna-action?tab=readme-ov-file#example-workflow-foundry, it is failing with:
```
echidna-test: Couldn't compile given file
[2024-07-03 16:36:15.82] Compiling test/echidna/CryticERC4626Harness.t.sol... Done! (0.100808046s)
stdout:
stderr:
INFO:CryticCompile:'forge config --json' running
Traceback (most recent call last):
  File "/venv/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/crytic_compile/__main__.py", line 220, in main
    compilations = compile_all(**vars(args))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 168, in __init__
    platform_config = platform_wd.config(str(self._working_dir))
  File "/venv/lib/python3.8/site-packages/crytic_compile/platform/foundry.py", line [133](https://github.com/euler-xyz/euler-aggregation-layer/actions/runs/9781621716/job/27006108650#step:5:136), in config
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'forge'
```

### Code example to reproduce the issue:

```
name: Echidna Test

on:
    push:
        branches:
            - main
    pull_request:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Compile contracts
      run: |
        forge build --build-info

    - name: Run Echidna
      uses: crytic/echidna-action@v2
      with:
        files: test/echidna/CryticERC4626Harness.t.sol
        contract: CryticERC4626Harness
        crytic-args: --foundry-ignore-compile --ignore-compile
```

### Version:

Echidna 2.2.3

### Relevant log output:

```shell
Echidna version: Echidna 2.2.3
Echidna command line: echidna-test test/echidna/CryticERC4626Harness.t.sol --contract CryticERC4626Harness --crytic-args --foundry-ignore-compile --ignore-compile

echidna-test: Couldn't compile given file
[2024-07-03 16:36:15.82] Compiling test/echidna/CryticERC4626Harness.t.sol... Done! (0.100808046s)
stdout:
stderr:
INFO:CryticCompile:'forge config --json' running
Traceback (most recent call last):
  File "/venv/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/crytic_compile/__main__.py", line 220, in main
    compilations = compile_all(**vars(args))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 168, in __init__
    platform_config = platform_wd.config(str(self._working_dir))
  File "/venv/lib/python3.8/site-packages/crytic_compile/platform/foundry.py", line 133, in config
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'forge'
```

**Comment by ggrieco-tob** [comment]
Thanks for your report. Can you move this report to the [echidna-action repository](https://github.com/crytic/echidna-action)  please?
