### ISSUE TITLE
Add a flag to disable slither integration

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#646]
We have a vyper workaround that skips slither but ideally we want allow the user to disable slither if it fails for some reason.

**Comment by avniculae** [comment]
Hey! Echidna fails with the following message `echidna: Error running slither:` (no text after colon). What's the current solution for disabling Slither in Echidna? As a side note, I'm not sure why Slither fails to be honest -- it worked well until I've brought in another contract into the fuzzing harness.

**Comment by avniculae** [comment]
Thanks for your quick reply! Here's the full error output.
<details>
  <summary>Error Traceback</summary>

```
'forge clean' running (wd: /path/.../)
'forge build --build-info --force' running
Compiling 150 files with 0.8.17
Solc 0.8.17 finished in 11.69s
Compiler run successful (with warnings)
[...warning info printed...]

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 837, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 101, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 79, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 528, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 739, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1761, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 681, in slithir_generation
    self._find_read_write_call()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 879, in _find_read_write_call
    assert isinstance(ir.function, Function)
AssertionError
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 837, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 101, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/__main__.py", line 79, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 528, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 739, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1761, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 681, in slithir_generation
    self._find_read_write_call()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.3/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 879, in _find_read_write_call
    assert isinstance(ir.function, Function)
AssertionError
```
</details>

**Comment by avniculae** [comment]
Hey @ggrieco-tob! Would you please be able to point me to how I can disable slither in echidna? I think the issue I'm encountering might be related to this one https://github.com/crytic/slither/issues/1622.

**Comment by ggrieco-tob** [comment]
This is still not implemented, the main reason is that we absolutely need slither to make sure echidna is effective in the code exploration but we can implement a workaround. @arcz can you take a look to this?

**Comment by avniculae** [comment]
Oh I see, I didn't know slither plays an important role in your fuzzing engine. It would be great if the bug could be fixed in slither so that the efficiency of code exploration is not compromised, but I'm not sure how much work this would entail @arcz.
