### ISSUE TITLE
echidna-test: Couldn't compile given file

### ISSUE THREAD

**Issue by banescusebi** [crytic/echidna#647]
Hey, I'm on macOS Big Sur trying to run the latest binary release (not via docker) and I'm getting the following error:

```
echidna-test: Couldn't compile given file
stdout:
stderr:
Traceback (most recent call last):
  File "/usr/local/bin/crytic-compile", line 33, in <module>
    sys.exit(load_entry_point('crytic-compile==0.1.12', 'console_scripts', 'crytic-compile')())
  File "/usr/local/lib/python3.9/site-packages/crytic_compile-0.1.12-py3.9.egg/crytic_compile/__main__.py", line 157, in main
    compilations = compile_all(**vars(args))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile-0.1.12-py3.9.egg/crytic_compile/crytic_compile.py", line 1076, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile-0.1.12-py3.9.egg/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile-0.1.12-py3.9.egg/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile-0.1.12-py3.9.egg/crytic_compile/platform/solc.py", line 180, in compile
    crytic_compile.abis[contract_name] = json.loads(info["abi"])
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
```

I use `solc-select` and have selected the right solc version and also successfully compiled the same contract using the `solc contract.sol` command. Any ideas of why this error is showing up?

**Comment by ggrieco-tob** [comment]
Interesting. Is it failing for any contracts? or can you provide the exact one?

**Comment by banescusebi** [comment]
It's failing for any contract I've tried so far. I've even tried it on the examples provided in this repo under https://github.com/crytic/echidna/blob/master/examples/solidity/

**Comment by ggrieco-tob** [comment]
Can you try compiling any contract directly using `crytic-compile`? If that fails, you should open an issue in the specific repository (https://github.com/crytic/crytic-compile)

**Comment by banescusebi** [comment]
Compiling using `crytic-compile` gives me that exact error. I will open an issue on the repo you indicated. Thanks!
