### ISSUE TITLE
[Errno 13] Permission denied: 'crytic-export'

### ISSUE THREAD

**Issue by iskdrews** [crytic/echidna#810]
I am getting this error although the contracts are compiled correctly outside the trailofbits/eth-security-toolbox docker image: 
```
echidna-test: Couldn't compile given file
stdout:
stderr:
Traceback (most recent call last):
  File "/home/ethsec/.local/bin/crytic-compile", line 11, in <module>
    sys.exit(main())
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/__main__.py", line 201, in main
    compilation.export(**vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 498, in export
    return PLATFORMS_EXPORT[export_format](self, **kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 117, in export_to_solc
    path = export_to_solc_from_compilation_unit(compilation_unit, "combined_solc", export_dir)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 90, in export_to_solc_from_compilation_unit
    os.makedirs(export_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'crytic-export'
```

### Versions:
1. solc: `0.8.9`
2. echidna-test: Echidna 2.0.1

**Comment by elopez** [comment]
Hi @iskdrews, thanks for the report. It looks like you don't have permissions to write on the target folder, you might want to check that you can write there. If you are sharing a host filesystem to inside the docker instance, you should check the files and folders' user and group IDs vs the ones from the docker instance user, in case that's causing a problem.
